/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Animation: typeof import('./src/components/business/home/ArticleList/Animation.vue')['default']
    Article: typeof import('./src/components/business/article/Article.vue')['default']
    ArticleHeader: typeof import('./src/components/business/article/ArticleHeader.vue')['default']
    ArticleList: typeof import('./src/components/business/home/ArticleList/ArticleList.vue')['default']
    ArticleListHeader: typeof import('./src/components/business/home/ArticleList/ArticleListHeader.vue')['default']
    Avatar: typeof import('./src/components/layout/Avatar.vue')['default']
    BackToTopTrigger: typeof import('./src/components/ui/BackToTopTrigger.vue')['default']
    CaptchaInput: typeof import('./src/components/ui/CaptchaInput.vue')['default']
    CategoryCard: typeof import('./src/components/business/CategoryCard.vue')['default']
    CollapseButton: typeof import('./src/components/ui/CollapseButton.vue')['default']
    CommentCard: typeof import('./src/components/business/article/CommentCard.vue')['default']
    DigitalClock: typeof import('./src/components/business/home/Rigth/DigitalClock.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    FormInput: typeof import('./src/components/ui/FormInput.vue')['default']
    GradientText: typeof import('./src/components/ui/gradient-text/GradientText.vue')['default']
    HotTagSection: typeof import('./src/components/business/home/Rigth/HotTagSection.vue')['default']
    InfiniteScrollContainer: typeof import('./src/components/business/InfiniteScrollContainer.vue')['default']
    LikeButton: typeof import('./src/components/business/article/LikeButton.vue')['default']
    LoadMore: typeof import('./src/components/ui/LoadMore.vue')['default']
    MainNavbar: typeof import('./src/components/layout/MainNavbar.vue')['default']
    'MarkdownBubble ': typeof import('./src/components/ui/MarkdownBubble .vue')['default']
    OnlineStatus: typeof import('./src/components/business/OnlineStatus.vue')['default']
    PascalCase: typeof import('./src/components/business/home/Rigth/PascalCase.vue')['default']
    Profile: typeof import('./src/components/business/Profile.vue')['default']
    ProfileSettingsCard: typeof import('./src/components/business/ProfileSettingsCard.vue')['default']
    RandomArticlePanel: typeof import('./src/components/business/home/Rigth/RandomArticlePanel.vue')['default']
    ReadingStatus: typeof import('./src/components/business/ReadingStatus.vue')['default']
    Remark: typeof import('./src/components/business/article/Remark.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarNoticePanel: typeof import('./src/components/business/home/Rigth/SidebarNoticePanel.vue')['default']
    SplashCursor: typeof import('./src/components/ui/splash-cursor/SplashCursor.vue')['default']
    Statement: typeof import('./src/components/business/article/Statement.vue')['default']
    StatsPanel: typeof import('./src/components/business/home/Rigth/StatsPanel.vue')['default']
    TextGlitch: typeof import('./src/components/business/home/TextGlitch.vue')['default']
    TypeWriterEffect: typeof import('./src/components/business/home/TypeWriterEffect.vue')['default']
    UnfavoriteConfirm: typeof import('./src/components/ui/UnfavoriteConfirm.vue')['default']
  }
}
